# 配置 服务器信息
server:
  port: 8090
  servlet:
    multipart:
      # 开启 multipart 上传功能
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
      # 最大文件大小
      max-file-size: 200MB
      # 最大请求大小
      max-request-size: 215MB
    session:
      timeout: 1

## 文件存储所需参数
# 所有通过 REST APIs 上传的文件都将存储在此目录下
file:
  upload-dir: ./img


spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  # 数据库信息配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  # 配置 redis 相关信息
  redis:
    host: localhost
    port: 6379
  # 配置 rabbitmq
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    addresses: 127.0.0.1
    #开启发送失败返回
    publisher-returns: true
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
      #开启ack
      direct:
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true


jwt:
  # token_header
  token_header: "x-authorization"
  # jwt prefix
  prefix: "tiro "
  # 秘钥
  secret: "secret"
  # 单位 ： 秒
  expiration: 60
logging:
  level:
    cn.cerish.mapper: debug
